menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/xzh97

favicon: /favicon.ico
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
gitalk:
    enable: true #用来做启用判断可以不用，目前没有写相关逻辑
    owner: xzh97 #Github 用户名,
    repo: xzh97.github.io #储存评论issue的github仓库名
    admin: ['xzh97'] #Github 用户名,
    oauth:
        clientID: 73f1c80bba01cb73e53d #`Github Application clientID`
        clientSecret: fb38d78684a17e97a441a4cd0db47dc642423678 #`Github Application clientSecret`
# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
